spring:
  application:
    name: forum-user-service
  config:
    server-addr: localhost:8848
    import:
      - nacos:forum-user-service.yaml?refresh=true
      - nacos:forum-common.yaml?refresh=true
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        # 服务注册到 Nacos
        enabled: true
    sentinel:
      transport:
        port: 8722
        dashboard: localhost:8858